"""
schemas.py
----------
Pydantic data models for the RazorShield Explanation Layer.
"""

from __future__ import annotations

from typing import Any, Literal
from pydantic import BaseModel, Field


class ExplanationInput(BaseModel):
    """Input structured evidence generated by RazorShield Risk/Incident Engines."""

    merchant_id: str = Field(..., description="Merchant ID")
    incident_state: Literal["NORMAL", "INVESTIGATE", "ALERT"] = Field(..., description="Incident state")
    severity: Literal["LOW", "MEDIUM", "HIGH"] = Field(..., description="Severity level")
    incident_score: float = Field(..., ge=0.0, le=1.0, description="Policy incident score")
    spike_probability: float = Field(..., ge=0.0, le=1.0, description="Spike probability")
    fraud_excess_ratio: float = Field(..., ge=0.0, description="Fraud excess ratio")
    velocity_ratio: float = Field(..., ge=0.0, description="Velocity ratio")
    suspicious_windows: int = Field(..., ge=0, description="Consecutive suspicious windows")
    total_suspicious_windows: int = Field(default=0, ge=0, description="Total suspicious windows")
    campaign_active: bool = Field(default=False, description="Whether campaign is active")
    policy_mode: str = Field(default="BALANCED", description="Policy operating mode")
    signals: list[dict[str, Any]] = Field(default_factory=list, description="Extracted evidence signals")
    recommended_action: str = Field(default="monitor", description="Engine recommended action")


class ExplanationOutput(BaseModel):
    """Structured JSON output produced by the SLM or Fallback system."""

    title: str = Field(..., description="Concise explanation title")
    summary: str = Field(..., description="Natural language explanation summary (60-120 words)")
    key_signals: list[str] = Field(default_factory=list, description="Key supporting evidence signals")
    campaign_context: str = Field(..., description="Impact of promotional campaign status")
    recommended_action: str = Field(..., description="Recommended defensive action")
    confidence_note: str = Field(..., description="Note on policy score and deterministic authority")


class GoldExpectation(BaseModel):
    """Ground-truth evaluation benchmark expectations for an evidence sample."""

    expected_incident_state: str = Field(..., description="Expected incident state")
    expected_severity: str = Field(..., description="Expected severity level")
    required_numeric_values: list[str] = Field(default_factory=list, description="Required numerical fields")
    required_signals: list[str] = Field(default_factory=list, description="Required signal names")
    campaign_status: bool = Field(..., description="Expected campaign active status")
    allowed_actions: list[str] = Field(default_factory=list, description="Allowed action keywords")
    forbidden_claims: list[str] = Field(default_factory=list, description="Forbidden ungrounded claims")
